### ISSUE TITLE
PDF could not be generated! Text file busy (Errno::ETXTBSY)

### ISSUE THREAD

**Issue by RichStone** [mileszs/wicked_pdf#1029]
Hey! 👋

## Issue description

I have a flaky test with PDF generation and I haven't found clues in Google or in the gem doc on how to solve it:

```
Error:
Mailer::InvoicePdfServiceTest#test_generate_PDF_via_instance_method:
RuntimeError: Failed to execute:
["/home/runner/work/app/app/vendor/bundle/ruby/2.7.0/gems/wkhtmltopdf-binary-0.12.6.5/bin/wkhtmltopdf", "--lowquality", "file:////tmp/wicked_pdf20220614-3447-1xqty3.html", "/tmp/wicked_pdf_generated_file20220614-3447-1la7wao.pdf"]
Error: PDF could not be generated!
 Command Error: /home/runner/work/app/app/vendor/bundle/ruby/2.7.0/gems/wkhtmltopdf-binary-0.12.6.5/bin/wkhtmltopdf:66:in `exec': Text file busy - /home/runner/work/app/app/vendor/bundle/ruby/2.7.0/gems/wkhtmltopdf-binary-0.12.6.5/bin/wkhtmltopdf_ubuntu_[18](https://github.com/WebinarGeek/app/runs/6874313692?check_suite_focus=true#step:9:19).04_amd64 (Errno::ETXTBSY)
	from /home/runner/work/app/app/vendor/bundle/ruby/2.7.0/gems/wkhtmltopdf-binary-0.12.6.5/bin/wkhtmltopdf:66:in `<main>'
    app/services/mailer/invoice_pdf_service.rb:12:in `generate_pdf'
    test/services/mailer/invoice_pdf_service_test.rb:10:in `block in <class:InvoicePdfServiceTest>'
```

It looks like [there's something wrong with the timing](https://stackoverflow.com/questions/16764946/what-generates-the-text-file-busy-message-in-unix), but I'm not sure what I'm doing wrong.

Im generating the PDF with something like this:

```ruby
    # InvoicePdfService
    def generate_pdf(invoice)
      WickedPdf.new.pdf_from_string(invoice)
    end
```

And then it's 

```ruby
  # Send customer invoice
  def invoice(email, invoice)
    invoice_pdf = InvoicePdfService.generate_pdf(invoice)
    attachments["invoice.pdf"] = {mime_type: "application/pdf", content: invoice_pdf}

    mail(to: email ....)
  end
```

Looks like there are no operations in between, but 2 similar tests are running in succession:

```ruby
class InvoicePdfServiceTest < ActiveSupport::TestCase
  setup do
    @service_class = Mailer::InvoicePdfService
    @invoice = FactoryBot.create(:invoice)
  end

  test "generate PDF via instance method" do
    pdf = @service_class.new(@invoice).generate_pdf

    assert_not_empty pdf
    assert pdf.start_with?("%PDF-1.4")
  end

  test "generate PDF via class method" do
    pdf = @service_class.generate_pdf(@invoice)

    assert_not_empty pdf
    assert pdf.start_with?("%PDF-1.4")
  end
end
```

However, they both create **new** instances of the PDF, so I'm not sure what's exactly blocking there 🤔

## Expected or desired behavior

Test runs through without error.

## System specifications

wicked_pdf gem version (output of `cat Gemfile.lock | grep wicked_pdf`):

```
    wicked_pdf (1.4.0)
  wicked_pdf (~> 1.4.0)
```

wkhtmltopdf version (output of `wkhtmltopdf --version`):

`wkhtmltopdf-binary-0.12.6.5`

```

whtmltopdf [provider gem](https://rubygems.org/search?utf8=%E2%9C%93&query=wkhtmltopdf) and version if one is used:

platform/distribution and version (e.g. Windows 10 / Ubuntu 16.04 / Heroku cedar):

ubuntu_18.04_amd64

**Comment by ilya-konanykhin** [comment]
Looking at the source code, seems the problem is like this: `wkthmltopdf-binary` gem stores binaries in `gz` and unpacks them at the first call. When running in parallel, the first invocation tries to unpack and the second invocation tries to run *while the unpacking is still in progress*.

So we should either prepare the unpacked version up front (run a dummy PDF command), or not run PDF generators in parallel (not sure if this is possible).

<img width="477" alt="Снимок экрана 2022-06-14 в 14 46 53" src="https://user-images.githubusercontent.com/8665049/173535907-52f84b62-55ca-42c8-9e16-9b3761a4ca5a.png">

**Comment by ilya-konanykhin** [comment]
Looks like it should be enough to add `bundle exec wkhtmltopdf --version` as a CI step before tests.

**Comment by ilya-konanykhin** [comment]
Let me do this while I'm on it.

**Comment by ghiculescu** [comment]
^ we implemented a wrapper to resolve this issue:

```ruby
class PdfBuilder
  def self.from_string(string)
    retries = 0
    begin
      WickedPdf.new.pdf_from_string(string)
    rescue RuntimeError
      if (retries += 1) <= 3
        sleep(retries)
        retry
      else
        raise
      end
    end
  end
end
```

**Comment by leurias** [comment]
I had this issue in my bitbucket pipeline, fixed with this patch, thanks @ghiculescu:
```ruby
# test/support/patchs/pdf_builder_patch.rb
class WickedPdf
  def pdf_from_string(string, options = {})
    retries = 0

    options = options.dup
    options.merge!(WickedPdf.config) { |_key, option, _config| option }
    string_file = WickedPdf::Tempfile.new('wicked_pdf.html', options[:temp_path])
    string_file.write_in_chunks(string)
    pdf_from_html_file(string_file.path, options)
  rescue
    pp "Retry pdf generation: #{retries}"
    raise unless (retries += 1) <= 10

    sleep(retries)
    retry
  ensure
    string_file.close if string_file
  end
end
```
