### ISSUE TITLE
Error: PDF could not be generated!

### ISSUE THREAD

**Issue by Dimasfullxq** [mileszs/wicked_pdf#1086]
## Error: PDF could not be generated!

I have an error while generating PDF, but sometimes it works. 1 of 100 tries
```[wicked_pdf]: ["/Users/dimasfullxq/.rvm/gems/ruby-3.2.1@online-consulting-backend/bin/wkhtmltopdf", "--enable-local-file-access", "file:////var/folders/ng/0095qts9355cdj2_cp18z14c0000gn/T/wicked_pdf20231219-33636-1krr8o.html", "/var/folders/ng/0095qts9355cdj2_cp18z14c0000gn/T/wicked_pdf_generated_file20231219-33636-jnjpi5.pdf"]
/Users/dimasfullxq/.rvm/gems/ruby-3.2.1@online-consulting-backend/gems/wicked_pdf-2.6.3/lib/wicked_pdf.rb:80:in `rescue in pdf_from_url': Failed to execute: (RuntimeError)
["/Users/dimasfullxq/.rvm/gems/ruby-3.2.1@online-consulting-backend/bin/wkhtmltopdf", "--enable-local-file-access", "file:////var/folders/ng/0095qts9355cdj2_cp18z14c0000gn/T/wicked_pdf20231219-33636-1krr8o.html", "/var/folders/ng/0095qts9355cdj2_cp18z14c0000gn/T/wicked_pdf_generated_file20231219-33636-jnjpi5.pdf"]
Error: PDF could not be generated!
 Command Error: Loading pages (1/6)
Counting pages (2/6)                                               
[============================================================] Object 1 of 1
/Users/dimasfullxq/.rvm/gems/ruby-3.2.1@online-consulting-backend/gems/wicked_pdf-2.6.3/lib/wicked_pdf.rb:76:in `pdf_from_url': PDF could not be generated! (RuntimeError)
 Command Error: Loading pages (1/6)
Counting pages (2/6)                                               
[============================================================] Object 1 of 1
```

## System specifications

wicked_pdf gem version (output of `cat Gemfile.lock | grep wicked_pdf`): 
wicked_pdf (2.6.3)
  wicked_pdf

wkhtmltopdf version (output of `wkhtmltopdf --version`): wkhtmltopdf 0.12.6 (with patched qt)

whtmltopdf [provider gem](https://rubygems.org/search?utf8=%E2%9C%93&query=wkhtmltopdf) and version if one is used: default binary

platform/distribution and version (e.g. Windows 10 / Ubuntu 16.04 / Heroku cedar): MacOs 14.1.2 (23B92), Intel

Rails 7.0.4 Ruby 3.2.1. 
WickedPdf.config = {
  enable_local_file_access: true
}

P.S Checked on test application with same rails and ruby version - works fine. Maybe you can support why I have such issue?

**Comment by slapsstick** [comment]
It's sound sad(
