### ISSUE TITLE
:footer and :header not working with wkhtmltopdf 0.11.0 rc1

### ISSUE THREAD

**Issue by Thomas233** [mileszs/wicked_pdf#153]
Hello,

first of all thank you for this great piece of software.

It`s working fine for me, but have one simple problem. I cannot generate documents with footers or headers. Everything else just works fine. 
If I use any of the footer or header options, the wkhtmltopdf process seems to crash.

```ruby
      format.pdf {
        render :pdf => pdf_filename(@invoice,false),
            :template => "invoices/generate",
            :layout => "document",
            :footer => {:content => render_to_string({:template => 'shared/_document_bottom'})}, # produces error - commented it out and it worked
            :show_as_html => params[:debug]
      }
```

>"C:\Program Files (x86)\wkhtmltopdf\wkhtmltopdf.exe"  --footer-html "file://C:/Users/Tommy/AppData/>Local/Temp/wicked_footer_pdf_5924_0.html"       - - 
>Error: PDF could not be generated!):
>  app/controllers/invoices_controller.rb:77:in `block (2 levels) in generate'
>  app/controllers/invoices_controller.rb:67:in `generate'

I assume this might be an incompatiblity between wkhtmltopdf 0.11 series and wicked_pdf ?

But if possible I would like to keep this version due to some fixes. What do you think ?

Thank you !

**Comment by gustaflindqvist** [comment]
I have the same problem with **0.11.0rc1 via Homebrew on Mac** and **0.12.0 on Ubuntu** (production). Using latest version of **Wicked_pdf 0.11.0**. I can’t see the footer or the header.

I can see that the footer is loaded in the console:

```
***************WICKED*************** 
  Rendered foo/show.pdf.erb within layouts/pdf.html.erb (206.3ms)
  Rendered shared/footer.pdf.erb within layouts/pdf.html.erb (0.1ms)
  Rendered text template (0.1ms)
Sent data SVC-10026-1502T2 - File 1.pdf (3.5ms)
Completed 200 OK in 5296ms (Views: 2.6ms | ActiveRecord: 64.7ms)
```

```ruby
        render pdf: @report_title,
               formats: [:html],
               orientation: ‘Landscape’,
               page_size: ‘A4’,
               dpi: ‘300’,
               show_as_html: params[:debug].present?,
               disable_smart_shrinking: true,
               template: ‘foo/show.pdf.erb’,
               layout: ‘pdf.html.erb’,
               footer: {
                html: {
                  template: ‘shared/footer.pdf.erb’,
                  locals: { title: @report_title }
                }
               }
```

If I adding the left, center and right in the footer I get exception.

```ruby
        render pdf: @report_title,
               formats: [:html],
               orientation: ‘Landscape’,
               page_size: ‘A4’,
               dpi: ‘300’,
               show_as_html: params[:debug].present?,
               disable_smart_shrinking: true,
               template: ‘foo/index.pdf.erb’,
               layout: ‘pdf.html.erb’,
               header: { right: ‘[page] of [topage]’ },
               footer: {
                        left: ‘Company,
                        center: ‘Custom text’,
                        right: ‘Test’
                       }
```
Exception with the command error:
```
Error: Failed to execute: [“/usr/local/bin/wkhtmltopdf”, “-q”, “—orientation”, “Landscape”, “—dpi”, “300”, “—page-size”, “A4”, “—header-right”, “[page] av [topage]”, “—disable-smart-shrinking”, “file:////tmp/wicked_pdf20150320-20347-8f5we5.html”, “/tmp/wicked_pdf_generated_file20150320-20347-1kwnp4f.pdf”] Error: PDF could not be generated! Command Error: 
```

**Comment by gustaflindqvist** [comment]
Mabye should put this into a new issue based on this issue is closed?

**Comment by unixmonkey** [comment]
No problem, I'll reopen this one.

**Comment by gustaflindqvist** [comment]
@unixmonkey awesome. Is there a way to trace wicked_pdf together with wkhtmltopdf? 

Feels like footer and header is overwritten.  Maybe I'm missing something in the template or the layout?

**Comment by unixmonkey** [comment]
My usual process is to "bundle open wicked_pdf" and drop "binding.pry" inside the gem code.




You'll need to restart the rails server every time you change gem code, since gems are only loaded on boot, and not on page reloads like most Rails app code.




When you are done debugging, make sure to undo your changes, or you can run "gem pristine wicked_pdf" to redownload the gem as fresh.



—
David Jones

**Comment by gustaflindqvist** [comment]
I'm back and I have finally investigate the prerender_header_and_footer method. This is what I'm getting (I have changed the code a bit)?

```
{:layout=>"pdf.html.erb",                                                 
 :orientation=>"Landscape",                                                  
 :page_size=>"A4",                                                           
 :dpi=>"300",                                                                
 :disable_smart_shrinking=>true,                                             
 :exe_path=>"/usr/local/bin/wkhtmltopdf",                                    
 :formats=>[:html],                                                          
 :show_as_html=>false,                                                       
 :template=>"foo/show.pdf.erb",                                        
 :header=>                                                                   
  {:html=>                                                                   
    {:template=>"shared/pdf/_header.pdf.erb",                                
     :layout=>"pdf.html.erb",                                                
     :url=>                                                                  
      "file:////var/folders/4l/sr_j9lds7q94j12pkzgp6dhc0000gn/T/wicked_header
_pdf20150410-83437-1xcjhlg.html"}},                                          
 :footer=>{:html=>{:template=>"shared/pdf/_footer.pdf.erb"}},                
 :basic_auth=>nil,                                                           
 :wkhtmltopdf=>nil,                                                          
 :disposition=>"inline"}
```
In the controller:
```ruby
       render pdf: @report_title,
               formats: [:html],
               show_as_html: params[:debug].present?,
               template: 'foo/show.pdf.erb',
               header: { html: { template: 'shared/pdf/_header.pdf.erb' } },
               footer: { html: { template: 'shared/pdf/_footer.pdf.erb' } }
```
In wicked_pdf.rb:
```ruby
WickedPdf.config = {
  layout: 'pdf.html.erb',
  orientation: 'Landscape',
  page_size: 'A4',
  dpi: '300',
  disable_smart_shrinking: true,
  exe_path: '/usr/local/bin/wkhtmltopdf',
}
```

**Comment by gustaflindqvist** [comment]
@unixmonkey Why I'm getting template, layout and url on header but not on footer? Or the input from wicked_pdf might be correct for wkhtmltopdf to handle?

**Comment by udaykiranreddy** [comment]
what do you have in footer ?

**Comment by gustaflindqvist** [comment]
@udaykiranreddy This issue can be closed. I upgrade to the lastest version of wkhtmltopdf. Then I got the header and footer to work. The trade-off was problem with Typekit instead, but that was ok.
