### ISSUE TITLE
Error: PDF could not be generated

### ISSUE THREAD

**Issue by samuel02** [mileszs/wicked_pdf#186]
Locally everything works like a charm, deployed to production, installed wkhtmltopdf by downloading the static with correct architecture (amd64) changed permissions to root, moved it to "/usr/bin". Changed tmp path.
#### Error

```
RuntimeError (Failed to execute:
"/usr/bin/wkhtmltopdf" -q     --margin-top 10 --margin-bottom 10 --margin-left 0 --margin-right 0  --dpi "300" --page-offset 0   "file:////home/railsusr/wkhtmltopdf_tmp/wicked_pdf20130130-4663-1ua00sk-0.h
tml" "/home/railsusr/wkhtmltopdf_tmp/wicked_pdf_generated_file20130130-4663-ha13oi-0.pdf" 
Error: PDF could not be generated!):
    /home/railsusr/eap/shared/bundle/ruby/1.8/gems/wicked_pdf-0.9.4/lib/wicked_pdf.rb:50:in `pdf_from_string'
    /home/railsusr/eap/shared/bundle/ruby/1.8/gems/wicked_pdf-0.9.4/lib/pdf_helper.rb:63:in `make_pdf'
    /home/railsusr/eap/shared/bundle/ruby/1.8/gems/wicked_pdf-0.9.4/lib/pdf_helper.rb:76:in `make_and_send_pdf'
    /home/railsusr/eap/shared/bundle/ruby/1.8/gems/wicked_pdf-0.9.4/lib/pdf_helper.rb:21:in `render'
    /app/controllers/reports_controller.rb:51:in `full_report'
```
#### Controller Action

``` ruby
respond_to do |format|
      format.pdf do
        render :pdf                     => "report_#{DateTime.now.strftime("%d%m%Y_%M%S")}",
               :show_as_html            => !params[:debug].nil? && params[:debug] == "true",
               :dpi                     => 300,
               :lowquality              => false,
               :page_offset             => 0,
               :wkhtmltopdf             => '/usr/bin/wkhtmltopdf',
               :temp_path               => '/home/railsusr/wkhtmltopdf_tmp',
               :margin => {:top         => 10,
                             :bottom    => 10,
                            :left        => 0,
                            :right       => 0}
      end
    end
```

I also tried to copy the command from the log and tried run it directly in the terminal, obviously changed input file but with the same output, it works great.

What is my problem!?
### System Details

wkhtmltopdf_amd64 0.11.0
Rails 2
Ruby 1.8.7
Passenger 3.0.19
Ubuntu 10.04.4

**Comment by nik-007** [comment]
thanks @ unixmonkey 
i was suffering from same issue , but your comments help me a lot and now everything is working great.
