### ISSUE TITLE
Unable to Find Template

### ISSUE THREAD

**Issue by msdundar** [mileszs/wicked_pdf#373]
I recently deployed my Rails 4 application to a Debian 7 server. I'm using Nginx+Passenger as web server with Ruby 2.1.5 and Rails 4.0.1. I'm getting this error when I try to get PDF export:

```
I, [2015-01-02T22:54:32.845650 #26215]  INFO -- : Processing by ParticipationsController#show as PDF
I, [2015-01-02T22:54:32.845746 #26215]  INFO -- :   Parameters: {"examination_id"=>"pedagojik-formasyon-vize-sinavi-pdg-2014", "id"=>"2"}
I, [2015-01-02T22:54:32.860635 #26215]  INFO -- : ***************WICKED***************
I, [2015-01-02T22:54:32.878144 #26215]  INFO -- :   Rendered participations/show.pdf.erb within layouts/pdf.html (15.9ms)
I, [2015-01-02T22:54:32.880179 #26215]  INFO -- : Completed 500 Internal Server Error in 34ms
F, [2015-01-02T22:54:32.882208 #26215] FATAL -- : 
ActionView::Template::Error (No such file or directory @ rb_sysopen - /srv/www/ais.uzem.omu.edu.tr/site/public/{:media=>"all"}.css):
    2: <html>
    3:   <head>
    4:     <meta charset='utf-8' />
    5:     <%= wicked_pdf_stylesheet_link_tag    "application", :media => "all" %>
    6:     <%= wicked_pdf_javascript_include_tag "application" %>
    7:     <%= csrf_meta_tags %>
    8:   </head>
  app/views/layouts/pdf.html.erb:5:in `_app_views_layouts_pdf_html_erb__1910077605281572593_69997218427040'
  app/controllers/participations_controller.rb:31:in `block (2 levels) in show'
  app/controllers/participations_controller.rb:28:in `show'
```

**Comment by maxfierke** [comment]
I'm assuming you figured this out because it's closed, but for people finding this later, simply remove the media declaration in the wicked_pdf_stylesheet_link_tag call.

**Comment by rapofran** [comment]
@maxfierke thanks for posting that!
:+1:
