### ISSUE TITLE
Installing plugin in Rails 2.3 - Generate can't find a source file

### ISSUE THREAD

**Issue by coreypmurphy** [mileszs/wicked_pdf#399]
ruby 1.8.7
rails 2.3.17
OSX 10.8.5
wicked_pdf 0.11.0
wkhtmltopdf-binary 0.9.9.3

Tried installing both gems and avoiding the plugin route but encountered issues with the WickedPdf class not being instantiated before the initializer file was being loaded. So I abandoned that route and followed the instructions for installing the plugin.

Running "script/plugin install git://github.com/mileszs/wicked_pdf.git" succeeded.
Running "script/generate wicked_pdf" command failed with the following error:

```ruby
/Users/corey/.rvm/rubies/ree-1.8.7-2012.02/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:29:in `gem_original_require': no such file to load -- wicked_pdf_tempfile (MissingSourceFile)
	from /Users/a028541/.rvm/rubies/ree-1.8.7-2012.02/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:29:in `require'
	from /Volumes/D/apps/sbtool/vendor/rails/activesupport/lib/active_support/dependencies.rb:182:in `require'
	from /Volumes/D/apps/sbtool/vendor/rails/activesupport/lib/active_support/dependencies.rb:547:in `new_constants_in'
	from /Volumes/D/apps/sbtool/vendor/rails/activesupport/lib/active_support/dependencies.rb:182:in `require'
	from /Volumes/D/apps/sbtool/vendor/plugins/wicked_pdf/init.rb:2:in `evaluate_init_rb'
	from ./script/../config/../vendor/rails/railties/lib/rails/plugin.rb:158:in `evaluate_init_rb'
	from /Volumes/D/apps/sbtool/vendor/rails/activesupport/lib/active_support/core_ext/kernel/reporting.rb:11:in `silence_warnings'
	from ./script/../config/../vendor/rails/railties/lib/rails/plugin.rb:154:in `evaluate_init_rb'
	from ./script/../config/../vendor/rails/railties/lib/rails/plugin.rb:48:in `load'
	from ./script/../config/../vendor/rails/railties/lib/rails/plugin/loader.rb:38:in `load_plugins'
	from ./script/../config/../vendor/rails/railties/lib/rails/plugin/loader.rb:37:in `each'
	from ./script/../config/../vendor/rails/railties/lib/rails/plugin/loader.rb:37:in `load_plugins'
	from ./script/../config/../vendor/rails/railties/lib/initializer.rb:369:in `load_plugins'
	from ./script/../config/../vendor/rails/railties/lib/initializer.rb:165:in `process'
	from ./script/../config/../vendor/rails/railties/lib/initializer.rb:113:in `send'
	from ./script/../config/../vendor/rails/railties/lib/initializer.rb:113:in `run'
	from /Volumes/D/apps/sbtool/config/environment.rb:10
	from /Users/a028541/.rvm/rubies/ree-1.8.7-2012.02/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:29:in `gem_original_require'
	from /Users/a028541/.rvm/rubies/ree-1.8.7-2012.02/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:29:in `require'
	from /Volumes/D/apps/sbtool/vendor/rails/railties/lib/commands/generate.rb:1
	from /Users/a028541/.rvm/rubies/ree-1.8.7-2012.02/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:29:in `gem_original_require'
	from /Users/a028541/.rvm/rubies/ree-1.8.7-2012.02/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:29:in `require'
	from script/generate:3
```

It seems that the call for the "WickedPdfTempfile" class in tempfile is being made in the init.rb file before "tempfile.rb" is even required.

**Comment by coreypmurphy** [comment]
The line in the init file is not pathed properly hence the original errors.  However even if it was pathed properly it would seem to me that it's an unnecessary require given it already gets required during the first require "wicked_pdf" in the init file.
