### ISSUE TITLE
colorspace error on created documents

### ISSUE THREAD

**Issue by tfitts** [mileszs/wicked_pdf#431]
I'm trying to render a pdf created using wickedpdf using a java pdf-renderer (https://java.net/jira/browse/PDF_RENDERER/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel)

and I'm getting 

java.lang.ArrayIndexOutOfBoundsException: 1
	at com.sun.pdfview.colorspace.PDFColorSpace.getColorSpace(PDFColorSpace.java:197)
	at com.sun.pdfview.PDFParser.parseColorSpace(PDFParser.java:1223)
	at com.sun.pdfview.PDFParser.iterate(PDFParser.java:641)
	at com.sun.pdfview.BaseWatchable.run(BaseWatchable.java:101)
	at java.lang.Thread.run(Unknown Source)

It seems to be this bug (https://java.net/jira/browse/PDF_RENDERER-84) which is 6 years old and probably not going to be fixed.

I'm wondering if there is a way or if a way can be made to manually set the colorspace when creating a document.

**Comment by unixmonkey** [comment]
I don't know, but [this `wkhtmltopdf` issue](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/39) (which wicked_pdf uses internally to do the PDF generation) seems to say no, but there are some workarounds linked in that thread.
