### ISSUE TITLE
Error: PDF could not be generated! Bundler::GemfileNotFound)

### ISSUE THREAD

**Issue by renegadeandy** [mileszs/wicked_pdf#564]
In production I am getting the following error:

`A RuntimeError occurred in listings#show_register:

  Error: Failed to execute:
["/opt/www/clazzoo/shared/bundle/ruby/2.2.0/gems/wkhtmltopdf-binary-0.9.9.3/bin/wkhtmltopdf", "-q", "file:////tmp/wicked_pdf20160810-20616-knltzu.html", "/tmp/wicked_pdf_generated_file20160810-20616-j8lj33.pdf"]
Error: PDF could not be generated!
 Command Error: /home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/definition.rb:23:in `build': /opt/www/clazzoo/releases/20160806020828/Gemfile not found (Bundler::GemfileNotFound)
        from /home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.rb:155:in `definition'
        from /home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.rb:123:in `setup'
        from /home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/setup.rb:18:in `<top (required)>'
        from /home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'

  app/controllers/listings_controller.rb:165:in `show_register'`

I have this file in my config/initializers/:

wicked_pdf.rb

`if Rails.env =="production" then
  WickedPdf.config = {
    exe_path: '/opt/www/clazzoo/shared/bundle/ruby/2.2.0/gems/wkhtmltopdf-binary-0.9.9.3/bin/wkhtmltopdf'
  }
end
`
I have this version of wicked_pdf:

  * wicked_pdf (1.0.6)
  * wkhtmltopdf-binary (0.9.9.3)

I cannot for the life of me work out what is wrong! help!

**Comment by Seunghyum** [comment]
I got same error and I solve with following method.

Did you check your config/initializers/mime_types.rb?

you must write this
`Mime::Type.register "application/pdf", :pdf`

I hope this answer solve your problem

**Comment by jrohrbaugh** [comment]
We're having this issue as well. One thing worth noting is that some code inside of WickedPdf is making a call to the Gemfile is trying to access an older release. Our application only keeps the five most recent releases, and this consistently causes every fifth release to trigger this error when we try and generate a PDF. 

@renegadeandy looks to be having the same issue. The tempfile `"file:////tmp/wicked_pdf20160810-20616-knltzu.html"` is dated 8/10, but the error trace `/opt/www/clazzoo/releases/20160806020828/Gemfile` is looking for the Gemfile from the 08/06 release. 

I have no idea what's causing this, but it seems to be happening for other users. https://github.com/mileszs/wicked_pdf/issues/497 describes the same situation, and has a similar release timestamp discrepancy.

**Comment by kurtsgm** [comment]
Same with @jrohrbaugh. wkhtmltopdf tried to access Gemfile of older release which is removed.

Command Error: /home/deployer/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:23:in `build': /var/www/tenk/releases/20180201083817/Gemfile not found (Bundler::GemfileNotFound)

However, my current release is 
lrwxrwxrwx 1 deployer deployer       41 Mar 29 11:11 current -> /var/www/tenk/releases/20180329111024
