### ISSUE TITLE
Error: PDF could not be generated!  Command Error: /usr/bin/env: ruby: Permission denied

### ISSUE THREAD

**Issue by aldompe95** [mileszs/wicked_pdf#667]
Im using the gem wicked_pdf and it works in development, but now im trying to generate the pdf in production didnt works.

This is my setup:

**gemfile.rb**
```
 gem 'wicked_pdf'
 gem 'wkhtmltopdf-binary'
```

**config/initializers/wicked_pdf.rb**
```
if Rails.env.production?
      WickedPdf.config = {
        exe_path: "#{ENV['GEM_HOME']}/gems/wkhtmltopdf-binary-#{Gem.loaded_specs['wkhtmltopdf-binary'].version}/bin/wkhtmltopdf"
      }
 end
```

**controlller/user_profile_controller.rb**
```
respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "ficha",:template => "user_profile/ficha.html.erb",viewport_size: '1280x1024'
      end 
end
```
_I already have my html view in /views/user_profile/ficha.html.erb_

**config/initializers/mime_types.rb**
`Mime::Type.register "application/pdf", :pdf`

**and this is the log error** 
```
[2017-07-11T02:15:48.470281 #1203]  INFO -- : Started GET "/user_profile/ficha.pdf?costo=50000&np=P03000826228f1&tipo_paquete=3" for 189.163.58.7 at 2017-07-11 02:15$
I, [2017-07-11T02:15:48.471522 #1203]  INFO -- : Processing by UserProfileController#ficha as PDF
I, [2017-07-11T02:15:48.471562 #1203]  INFO -- :   Parameters: {"costo"=>"50000", "np"=>"P03000826228f1", "tipo_paquete"=>"3"}
D, [2017-07-11T02:15:48.473117 #1203] DEBUG -- :   ^[[1m^[[36mUser Load (0.1ms)^[[0m  ^[[1mSELECT  "users".* FROM "users" WHERE "users"."id" = ?  ORDER BY "users"."id" $
I, [2017-07-11T02:15:48.473500 #1203]  INFO -- : ***************WICKED***************
I, [2017-07-11T02:15:48.526317 #1203]  INFO -- :   Rendered user_profile/ficha.html.erb (52.5ms)
I, [2017-07-11T02:15:48.529900 #1203]  INFO -- : Completed 500 Internal Server Error in 58ms (ActiveRecord: 0.1ms)
F, [2017-07-11T02:15:48.531137 #1203] FATAL -- :
RuntimeError (Failed to execute:
["/home/fideimx/ruby/gems/gems/wkhtmltopdf-binary-0.12.3.1/bin/wkhtmltopdf", "-q", "--viewport-size", "1280x1024", "file:////tmp/wicked_pdf20170711-1203-1hx1m0w.html", $
Error: PDF could not be generated!
 Command Error: /usr/bin/env: ruby: Permission denied
):
  app/controllers/user_profile_controller.rb:180:in `block (2 levels) in ficha'
  app/controllers/user_profile_controller.rb:177:in `ficha'

```

**Comment by unixmonkey** [comment]
There's no `/usr/bin/env ruby` in WickedPDF.

Perhaps your exe_path is actually a binstub file? Looks like you need to check permissions on it.

**Comment by aldompe95** [comment]
@unixmonkey what do you mean by binsub? i did  ` which wkhtmltopdf` and it says its in /ruby/gems/bin/wkhtmltopdf so i comment the WickedPdf.config in wicked_pdf.rb, im having the same error, i even did chmod 777 /ruby/gems/bin/wkhtmltopdf, but still the same error.

**Comment by aldompe95** [comment]
my app works fine until i need to generate the pdfs.

**Comment by unixmonkey** [comment]
A binstub is a file that is executable that executes a third party program. Bundler, Rbenv, and other systems use them to have a convenient executable to call the real program.

I think the path you are supplying is to a binstub, and not the wkhtmltopdf binary.
If you opened up this file:

```ruby
"#{ENV['GEM_HOME']}/gems/wkhtmltopdf-binary-#{Gem.loaded_specs['wkhtmltopdf-binary'].version}/bin/wkhtmltopdf"
```

You'll likely see it [looks like this](https://github.com/zakird/wkhtmltopdf_binary_gem/blob/master/bin/wkhtmltopdf).

Which should be fine, but it appears your server doesn't have a `/usr/bin/env ruby`, or the permissions on the file don't allow the server to execute the file.

Try pointing to the actual binary like:

```ruby
"#{ENV['GEM_HOME']}/gems/wkhtmltopdf-binary-#{Gem.loaded_specs['wkhtmltopdf-binary'].version}/bin/wkhtmltopdf_linux_amd64"
```

(or whatever your architecture is), and checking the permissions of the file being executed.

**Comment by douglasrosa0110** [comment]
Just grant permissions to your gems path:
1. `cd .rvm/gems/<your-actual-ruby-version>/gems/`
2. `sudo chmod -R 777 .`

**Comment by seshna** [comment]
i found my solution for this here https://qiita.com/fgem28/items/4b6f5bb61efcb8c37966
I am using wicked_pdf in rails, deploying to an EC2 instance via elastic beanstalk.
Following the website, with some slight changes, this is what worked for me

```ruby
# Gemfile
gem 'wicked_pdf'
gem 'wkhtmltopdf-binary-aml'
```

```ruby
# wicked_pdf.rb
WickedPdf.config = {
  exe_path: "#{Gem.loaded_specs['wkhtmltopdf-binary-aml'].full_gem_path}/bin/wkhtmltopdf-linux-amd64"
}
```
