### ISSUE TITLE
undefined method `wicked_pdf_stylesheet_link_tag' for #<ActionView::Base:0x00000009d11858>

### ISSUE THREAD

**Issue by vishaltps** [mileszs/wicked_pdf#717]
Its very weird type of issue . and not its become headache for me .

i am generating PDF with background job . i used [https://github.com/collectiveidea/delayed_job_active_record](delayed_job) for generating PDF 
  in background 

I used AWS Classic load balancer for my application. earlier everything was working fine but from last 30 days whenever new instance generate i need to restart the delayed job for successful generation of PDF.
if i don't restart the delayed job than i get below error .

> undefined method `wicked_pdf_stylesheet_link_tag' for #<ActionView::Base:0x00000009d11858>\n/var/www/project/lessons-matchmaker/app/views/instructor/home/group_classes_pdf.html.erb:2:in `_app_views_instructor_home_group_classes_pdf_html_erb___1024770791689151783_83694240'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/actionview-4.1.1/lib/action_view/template.rb:145:in `block in render'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/activesupport-4.1.1/lib/active_support/notifications.rb:161:in `instrument'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/actionview-4.1.1/lib/action_view/template.rb:339:in `instrument'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/actionview-4.1.1/lib/action_view/template.rb:143:in `render'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/actionview-4.1.1/lib/action_view/renderer/template_renderer.rb:55:in `block (2 levels) in render_template'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/actionview-4.1.1/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/activesupport-4.1.1/lib/active_support/notifications.rb:159:in `block in instrument'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/activesupport-4.1.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/activesupport-4.1.1/lib/active_support/notifications.rb:159:in `instrument'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/actionview-4.1.1/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/actionview-4.1.1/lib/action_view/renderer/template_renderer.rb:54:in `block in render_template'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/actionview-4.1.1/lib/action_view/renderer/template_renderer.rb:62:in `render_with_layout'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/actionview-4.1.1/lib/action_view/renderer/template_renderer.rb:53:in `render_template'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/actionview-4.1.1/lib/action_view/renderer/template_renderer.rb:17:in `render'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/actionview-4.1.1/lib/action_view/renderer/renderer.rb:42:in `render_template'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/actionview-4.1.1/lib/action_view/renderer/renderer.rb:23:in `render'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/actionview-4.1.1/lib/action_view/helpers/rendering_helper.rb:32:in `render'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/haml-4.1.0.beta.1/lib/haml/helpers/action_view_mods.rb:12:in `render_with_haml'\n/var/www/project/lessons-matchmaker/app/services/pdf_generator.rb:36:in `call'\n/var/www/project/lessons-matchmaker/app/mailers/classes_pdf_mailer.rb:5:in `send_classes_details'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/actionpack-4.1.1/lib/abstract_controller/base.rb:189:in `process_action'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/actionpack-4.1.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:82:in `run_callbacks'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/actionpack-4.1.1/lib/abstract_controller/callbacks.rb:19:in `process_action'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/actionpack-4.1.1/lib/abstract_controller/base.rb:136:in `process'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/actionview-4.1.1/lib/action_view/rendering.rb:30:in `process'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/actionmailer-4.1.1/lib/action_mailer/base.rb:580:in `block in process'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/activesupport-4.1.1/lib/active_support/notifications.rb:159:in `block in instrument'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/activesupport-4.1.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/activesupport-4.1.1/lib/active_support/notifications.rb:159:in `instrument'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/actionmailer-4.1.1/lib/action_mailer/base.rb:577:in `process'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/actionmailer-4.1.1/lib/action_mailer/base.rb:568:in `initialize'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/actionmailer-4.1.1/lib/action_mailer/base.rb:551:in `new'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/actionmailer-4.1.1/lib/action_mailer/base.rb:551:in `method_missing'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/performable_mailer.rb:6:in `perform'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:94:in `block in invoke_job'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:91:in `invoke_job'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block (2 levels) in run'\n/usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'\n/usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/timeout.rb:101:in `call'\n/usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/timeout.rb:101:in `timeout'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block in run'\n/usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/worker.rb:203:in `run'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `block in reserve_and_run_one_job'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `reserve_and_run_one_job'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/worker.rb:187:in `block in work_off'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `times'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `work_off'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/worker.rb:150:in `block (4 levels) in start'\n/usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/worker.rb:149:in `block (3 levels) in start'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/worker.rb:148:in `block (2 levels) in start'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `loop'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `block in start'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `call'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block in add'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/worker.rb:146:in `start'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/command.rb:124:in `run'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/command.rb:112:in `block in run_process'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/command.rb:110:in `run_process'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/command.rb:91:in `block in daemonize'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/command.rb:89:in `times'\n/usr/local/rvm/gems/ruby-2.1.2@ssa/gems/delayed_job-4.0.6/lib/delayed/command.rb:89:in `daemonize'\nbin/delayed_job:5:in `<main>'

Please help me to resolve this issue ASAP

**Comment by unixmonkey** [comment]
It's hard to tell what your issue is without more information. It sounds to me like Delayed Job classes may not have access to view helpers, but you say it worked for a long time and only recently changed, and that restarting DJ helps. Does the process of generating a new instance mean it is loaded without pre-loading necessary code (like ActionView)?

**Comment by vishaltps** [comment]
@unixmonkey  when the new instance is generated that time it will pull the latest code from master branch, and  run necessary commands like bundle install, rake db:migrate and etc.

**Comment by unixmonkey** [comment]
I suspect those "necessary commands" are either missing booting up of Rails, or more likely booting up your delayed workers before Rails is available to them.

**Comment by vishaltps** [comment]
But earlier everything works fine. can you help me how to resolve this issue ?

**Comment by cesc1989** [comment]
@vishaltps show the code that generates the PDF and tell the version of `wicked_pdf` you're using
