### ISSUE TITLE
RuntimeError: PDF could not be generated! WARN: /Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/wicked_pdf-1.1.0/lib/wicked_pdf.rb:88:in `pdf_from_url'

### ISSUE THREAD

**Issue by idknox** [mileszs/wicked_pdf#747]
Hi, I've been using wicked_pdf and wkhtmltopdf-binary for months with no issues and today began seeing an error:

wicked_pdf 1.1.0
wkhtmltopdf-binary 0.12.4
sidekiq 3.5.0

```"***************[\"/Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/bin/wkhtmltopdf\", \"-q\", \"--margin-top\", \"25\", \"--margin-bottom\", \"50\", \"--header-html\", \"file:////var/folders/cl/syjm9nnn0cg6ng8gp52bgw2c0000gn/T/wicked_header_pdf20180629-33891-dsjfyr.html\", \"--footer-html\", \"file:////var/folders/cl/syjm9nnn0cg6ng8gp52bgw2c0000gn/T/wicked_footer_pdf20180629-33891-15c9c27.html\", \"file:////var/folders/cl/syjm9nnn0cg6ng8gp52bgw2c0000gn/T/wicked_pdf20180629-33891-15fsilb.html\", \"/var/folders/cl/syjm9nnn0cg6ng8gp52bgw2c0000gn/T/wicked_pdf_generated_file20180629-33891-12dlhi6.pdf\"]***************"
/Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/sidekiq-3.5.0/lib/sidekiq/middleware/server/retry_jobs.rb:166: warning: constant ::Fixnum is deprecated
2018-06-30T01:24:19.326Z 33891 TID-owtfqekiw PdfPreviewWorker JID-f85f38426caca1ea4ed38245 INFO: fail: 39.205 sec
2018-06-30T01:24:19.328Z 33891 TID-owtfqekiw WARN: {"class"=>"PdfPreviewWorker", "args"=>[27120], "retry"=>3, "queue"=>"previews", "jid"=>"f85f38426caca1ea4ed38245", "created_at"=>1530321641.531851, "enqueued_at"=>1530321820.1184158, "error_message"=>"PDF could not be generated!\n Command Error: ", "error_class"=>"RuntimeError", "failed_at"=>1530321684.103435, "retry_count"=>2, "retried_at"=>1530321859.325151}
2018-06-30T01:24:19.328Z 33891 TID-owtfqekiw WARN: RuntimeError: PDF could not be generated!
 Command Error: 
2018-06-30T01:24:19.328Z 33891 TID-owtfqekiw WARN: /Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/wicked_pdf-1.1.0/lib/wicked_pdf.rb:88:in `pdf_from_url'
/Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/wicked_pdf-1.1.0/lib/wicked_pdf.rb:49:in `pdf_from_html_file'
/Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/wicked_pdf-1.1.0/lib/wicked_pdf.rb:60:in `pdf_from_string'
/Users/knoxid/ck/pla-po-rails/app/workers/pdf_preview_worker.rb:45:in `pdf'
/Users/knoxid/ck/pla-po-rails/app/workers/pdf_preview_worker.rb:22:in `block (3 levels) in perform'
/Users/knoxid/ck/pla-po-rails/app/workers/pdf_preview_worker.rb:21:in `open'
/Users/knoxid/ck/pla-po-rails/app/workers/pdf_preview_worker.rb:21:in `block (2 levels) in perform'
/Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/i18n-0.9.5/lib/i18n.rb:268:in `with_locale'
/Users/knoxid/ck/pla-po-rails/app/workers/pdf_preview_worker.rb:20:in `block in perform'
/Users/knoxid/ck/pla-po-rails/app/workers/pdf_preview_worker.rb:19:in `each'
/Users/knoxid/ck/pla-po-rails/app/workers/pdf_preview_worker.rb:19:in `perform'
/Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/sidekiq-3.5.0/lib/sidekiq/processor.rb:75:in `execute_job'
/Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/sidekiq-3.5.0/lib/sidekiq/processor.rb:52:in `block (2 levels) in process'
/Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/sidekiq-3.5.0/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/rollbar-2.15.0/lib/rollbar/plugins/sidekiq/plugin.rb:11:in `call'
/Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/sidekiq-3.5.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/newrelic_rpm-4.1.0.333/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'
/Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/newrelic_rpm-4.1.0.333/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:362:in `perform_action_with_newrelic_trace'
/Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/newrelic_rpm-4.1.0.333/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'
/Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/sidekiq-3.5.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/sidekiq-3.5.0/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/sidekiq-3.5.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/sidekiq-3.5.0/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/sidekiq-3.5.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/sidekiq-3.5.0/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/sidekiq-3.5.0/lib/sidekiq/logging.rb:30:in `with_context'
/Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/sidekiq-3.5.0/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/sidekiq-3.5.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/sidekiq-3.5.0/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/sidekiq-3.5.0/lib/sidekiq/processor.rb:51:in `block in process'
/Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/sidekiq-3.5.0/lib/sidekiq/processor.rb:98:in `stats'
/Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/sidekiq-3.5.0/lib/sidekiq/processor.rb:50:in `process'
/Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/celluloid-0.17.1.2/lib/celluloid/calls.rb:28:in `public_send'
/Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/celluloid-0.17.1.2/lib/celluloid/calls.rb:28:in `dispatch'
/Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/celluloid-0.17.1.2/lib/celluloid/call/async.rb:7:in `dispatch'
/Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/celluloid-0.17.1.2/lib/celluloid/cell.rb:50:in `block in dispatch'
/Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/celluloid-0.17.1.2/lib/celluloid/cell.rb:76:in `block in task'
/Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/celluloid-0.17.1.2/lib/celluloid/actor.rb:339:in `block in task'
/Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/celluloid-0.17.1.2/lib/celluloid/task.rb:44:in `block in initialize'
/Users/knoxid/.rvm/gems/ruby-2.4.4@railsapp/gems/celluloid-0.17.1.2/lib/celluloid/task/fibered.rb:14:in `block in create'
```

I have attempted: 

- uninstalling all gems and using wicked_pdf master and wkhtmltopdf-binary-edge
- even blew away my local codebase and pulled down a fresh folder with new gemset, etc.

Google yielded nothing helpful. Any help is greatly appreciated, thanks!

**Comment by unixmonkey** [comment]
Hm. Does it work with `wkhtmltopdf-binary 0.12.3.1`? That got updated pretty recently.

What platform/distribution are you running on?

**Comment by idknox** [comment]
Yeah we've been using that version. I also tried switching to the most recent stable version of wkhtmltopdf from their site, same behavior.

I'm seeing the same behavior on OSX 10.12.6 and on CentOS 7.5.1804

**Comment by unixmonkey** [comment]
Can you run `wkhtmltopdf` from the command-line? Something like this:

```shell
wkhtmltopdf https://google.com google.pdf
```

**Comment by idknox** [comment]
Yeah that runs just fine.

**Comment by unixmonkey** [comment]
Oh, wow. Can you reproduce it in a minimal example, something like this, but with those characters, so that I can try to help debug?

```ruby
pdf = WickedPdf.new.pdf_from_string('<!doctype html><html><head><title>Hey</title></head><body><h1>Hello</h1></body></html>')
File.open('test.pdf', 'wb') { |f| f << pdf }
```

You may try adding `<meta charset='utf-8' />` to your `<head>` if you haven't already.

Does it behave similarly in your dev environment as prod (or are they exactly the same)?

**Comment by idknox** [comment]
Yeah it behaves the same way on my stage AWS server. I'll try to narrow down which character(s) it is.

**Comment by idknox** [comment]
I was able to resolve this. For some reason, an inner join on the DB query used to populate the HTML was causing the converter to timeout or something. The app could render the HTML page just fine, but wkhtmltopdf couldn't handle it. Removed the join and it works fine now. Weird that it would fail so ambiguously due to that. Thanks for your help in troubleshooting.
