### ISSUE TITLE
SystemStackError with rspec in 1.4.0

### ISSUE THREAD

**Issue by P9GIT** [mileszs/wicked_pdf#845]
## System specifications

wicked_pdf gem version (output of `cat Gemfile.lock | grep wicked_pdf`):

wkhtmltopdf version (output of `wkhtmltopdf --version`):

whtmltopdf [provider gem](https://rubygems.org/search?utf8=%E2%9C%93&query=wkhtmltopdf) and version if one is used:

platform/distribution and version (e.g. Windows 10 / Ubuntu 16.04 / Heroku cedar):

**Comment by hbda** [comment]
Same problem arise if method render overided in controller. method(:render) return render from controller. And super_method for it return WickedPdf::PdfHelper#render.  
```
     ...
     # ./app/controllers/application_controller.rb:70:in `render'
     # /Users/dborisov/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/wicked_pdf-1.4.0/lib/wicked_pdf/pdf_helper.rb:46:in `call'
     # /Users/dborisov/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/wicked_pdf-1.4.0/lib/wicked_pdf/pdf_helper.rb:46:in `render_with_wicked_pdf'
     # /Users/dborisov/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/wicked_pdf-1.4.0/lib/wicked_pdf/pdf_helper.rb:30:in `render'
     # ./app/controllers/application_controller.rb:70:in `render'
     # /Users/dborisov/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/wicked_pdf-1.4.0/lib/wicked_pdf/pdf_helper.rb:46:in `call'
     # /Users/dborisov/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/wicked_pdf-1.4.0/lib/wicked_pdf/pdf_helper.rb:46:in `render_with_wicked_pdf'
     # /Users/dborisov/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/wicked_pdf-1.4.0/lib/wicked_pdf/pdf_helper.rb:30:in `render'
     # ./app/controllers/application_controller.rb:70:in `render'
     ...
```
Error occur not only in rspec. Requestion controller in normal mode leads to SystemStackError too.

**Comment by Epigene** [comment]
We're also getting this on any version beyond 1.1. I think @hbda is on the right track - it's something to do with overriding and, perhaps, the way Rails5+ has moved from `override_method_chain` to `Module#prepend`.

**Comment by ericproulx** [comment]
With the latest version of `rspec-rails`, `4.0.0`, we have the issue
```
/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/wicked_pdf-1.4.0/lib/wicked_pdf/pdf_helper.rb:46:in `call'",
 "/Users/eproulx/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/wicked_pdf-1.4.0/lib/wicked_pdf/pdf_helper.rb:46:in `render_with_wicked_pdf'",
 "/Users/eproulx/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/wicked_pdf-1.4.0/lib/wicked_pdf/pdf_helper.rb:30:in `render'",
 "/Users/eproulx/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/wicked_pdf-1.4.0/lib/wicked_pdf/pdf_helper.rb:46:in `call'",
 "/Users/eproulx/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/wicked_pdf-1.4.0/lib/wicked_pdf/pdf_helper.rb:46:in `render_with_wicked_pdf'",
 "/Users/eproulx/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/wicked_pdf-1.4.0/lib/wicked_pdf/pdf_helper.rb:30:in `render'",
 "/Users/eproulx/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/wicked_pdf-1.4.0/lib/wicked_pdf/pdf_helper.rb:46:in `call'",
 "/Users/eproulx/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/wicked_pdf-1.4.0/lib/wicked_pdf/pdf_helper.rb:46:in `render_with_wicked_pdf'",
 "/Users/eproulx/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/wicked_pdf-1.4.0/lib/wicked_pdf/pdf_helper.rb:30:in `render'",
 "/Users/eproulx/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/wicked_pdf-1.4.0/lib/wicked_pdf/pdf_helper.rb:46:in `call'",
 "/Users/eproulx/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/wicked_pdf-1.4.0/lib/wicked_pdf/pdf_helper.rb:46:in `render_with_wicked_pdf'",
 "/Users/eproulx/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/wicked_pdf-1.4.0/lib/wicked_pdf/pdf_helper.rb:30:in `render'",
 "/Users/eproulx/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/wicked_pdf-1.4.0/lib/wicked_pdf/pdf_helper.rb:46:in `call'",
```
We have a spec that does
```ruby
expect(controller).to receive(:render).with(plain: :calendar).and_call_original
```
