### ISSUE TITLE
ActionView::Template::Error: wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by jasonadkison** [mileszs/wicked_pdf#882]
## Issue description

I'm having an issue with controller specs. My implementation of wicked_pdf is purely backend, only using pdf_from_string. I'm only using the wicked_pdf helpers in a specific layout that's not currently being tested. 

```bash
ActionView::Template::Error: wrong number of arguments (given 2, expected 1)
# /usr/local/bundle/bundler/gems/wicked_pdf-0d96b8a73fb0/lib/wicked_pdf/pdf_helper.rb:46:in `call'
# /usr/local/bundle/bundler/gems/wicked_pdf-0d96b8a73fb0/lib/wicked_pdf/pdf_helper.rb:46:in `render_with_wicked_pdf'
# /usr/local/bundle/bundler/gems/wicked_pdf-0d96b8a73fb0/lib/wicked_pdf/pdf_helper.rb:30:in `render'
# ./app/controllers/example_controller.rb:11:in `show'
# /usr/local/bundle/gems/react-rails-2.6.1/lib/react/rails/controller_lifecycle.rb:31:in `use_react_component_helper'
# ./spec/controllers/example_controller_spec.rb:13:in `block (4 levels) in <main>'
# ./spec/rails_helper.rb:77:in `block (3 levels) in <top (required)>'
# /usr/local/bundle/gems/database_cleaner-1.8.0.beta/lib/database_cleaner/generic/base.rb:16:in `cleaning'
# /usr/local/bundle/gems/database_cleaner-1.8.0.beta/lib/database_cleaner/configuration.rb:87:in `block (2 levels) in cleaning'
# /usr/local/bundle/gems/database_cleaner-1.8.0.beta/lib/database_cleaner/configuration.rb:88:in `cleaning'
# ./spec/rails_helper.rb:76:in `block (2 levels) in <top (required)>'
# ------------------
# --- Caused by: ---
# ArgumentError:
#   wrong number of arguments (given 2, expected 1)
#   /usr/local/bundle/bundler/gems/wicked_pdf-0d96b8a73fb0/lib/wicked_pdf/pdf_helper.rb:46:in `call'
```

## Expected or desired behavior
Controller specs should work.

## System specifications

debian 10.2 (buster)
ruby 2.6.5
rails 6.0.2.1
rspec-rails 3.9.0
wicked_pdf 1.4.0 (and master)
wkhtmltopdf 0.12.4 (with patched qt)

**Comment by jasonadkison** [comment]
This turned out to be an issue with the [rspec-rails](https://github.com/rspec/rspec-rails) gem and not wicked_pdf. 

See [https://github.com/rspec/rspec-rails/issues/2177](https://github.com/rspec/rspec-rails/issues/2177)

The fix for me was `gem 'rspec-rails', '4.0.0.beta4'`.
