### ISSUE TITLE
Error: PDF could not be generated!  Command Error: Loading pages (1/6)

### ISSUE THREAD

**Issue by tsolar** [mileszs/wicked_pdf#954]
## Issue description
I am running a rails 6 app, using last version of wicked_pdf (2.1.0) and wkhtmltopdf-binary (0.12.6.5). 

I needed to reinstall everything because I installed a new SSD drive, so I wanted to start fresh, a clean and fresh install.

I installed everything, everything works fine until I got this
```
RuntimeError (Failed to execute:
["/home/tom/.rbenv/versions/2.6.3/gemsets/migrante-arc/bin/wkhtmltopdf", "--encoding", "UTF-8", "--lowquality", "file:////tmp/wicked_pdf20201111-111564-fn71lx.html", "/tmp/wicked_pdf_generated_file20201111-111564-9g9y4j.pdf"]
Error: PDF could not be generated!
 Command Error: Loading pages (1/6)
):=============================>                             ] 50%
  ```
If I run the command "outside" rails, it works, as described here: https://github.com/zakird/wkhtmltopdf_binary_gem/pull/99

I installed wkhtmltopdf from my distro repos (`apt install wkhtmltopdf`), in order to set `exe_path: /usr/bin/wkhtmltopdf`, and it works without any errors, as expected.

What am I missing? :(

## Expected or desired behavior

Get no errors (no RuntimeError)

## System specifications

wicked_pdf gem version (output of `cat Gemfile.lock | grep wicked_pdf`):
```
     wicked_pdf (2.1.0)
  wicked_pdf
```
wkhtmltopdf version (output of `wkhtmltopdf --version`):

* using rbenv and ruby 2.6.3: wkhtmltopdf 0.12.6 (with patched qt)

* output from `/usr/bin/wkhtmltopdf -- version` (Debian unstable package version): wkhtmltopdf 0.12.6

whtmltopdf [provider gem](https://rubygems.org/search?utf8=%E2%9C%93&query=wkhtmltopdf) and version if one is used: 
wkhtmltopdf-binary 0.12.6.5 

platform/distribution and version (e.g. Windows 10 / Ubuntu 16.04 / Heroku cedar):
Debian unstable (sid)

**Comment by unixmonkey** [comment]
It looks to me like it started working, but it stalled somewhere in the middle. This indicates to me that while rendering, it hit an asset that it needs to read over HTTP from the same server.

If you are in the process of re-setting things up, you may be running your Rails server in a single-threaded mode, instead of multithreaded with something like Puma, or running Puma with a single thread (`ENV['MAX_THREADS']`).

If this is what's happening, your first request hits localhost, which begins to render the ERB template, but stops to make a request to fetch the data from an asset (images, js, css), which makes a request-within-a-request, but if your server isn't configured to handle simultaneous requests, it get stuck in a deadlock, and the request never finishes.

I'm not 100% sure this is what's happening, but it sure sounds like it.

Please let me know if this helps, or if you find it's something else!

**Comment by tsolar** [comment]
Thanks for the quick reply!

It kinda makes sense. But what makes me doubt is that the binary from the Debian distribution works, but the binary from the wkhtmltopdf-binary gem doesn't (using it throws this error) :thinking:

**Comment by tsolar** [comment]
Could it be an issue due to the version of Qt on my system? Since I use Debian sid and the binary from the repos works, I am assuming it is compiled with the last Qt? And the binary on the gem is not using the same version? 

The thing that is making me think about it is this commit https://github.com/wkhtmltopdf/wkhtmltopdf/commit/451d82bae3a5302d6bcd3d193e57fc1f3760883e

So maybe it isn't a wicked_pdf issue but a wkhtmltopdf_binary_gem one? :thinking:

**Comment by unixmonkey** [comment]
@tsolar Could be. If you run the command by hand on the command line on your system, do you get an error message?

```shell
/home/tom/.rbenv/versions/2.6.3/gemsets/migrante-arc/bin/wkhtmltopdf --encoding UTF-8 --lowquality /tmp/wicked_pdf20201111-111564-fn71lx.html /tmp/wicked_pdf_generated_file20201111-111564-9g9y4j.pdf
```

What about if you use the system `wkthmltopdf`?

**Comment by tsolar** [comment]
Thanks for the reply!

I cannot (or i don't know how...) capture that temporary tmp file that wicked generates... but as I said in the first post, running it outside rails the binary from the gem works. And using the system `wkhtmltopdf` with rails setting it on wicked_pdf config `exe_path` works.

**Comment by unixmonkey** [comment]
@tsolar If you `bundle open wicked_pdf`, you can change `tempfile.close!` to `tempfile.close` and re-start your app, or point your `Gemfile` at the `master` branch, which already has that change:
```ruby
gem 'wicked_pdf', git: 'https://github.com/mileszs/wicked_pdf.git', branch: 'master'
```
That should keep the file around for a period of time after running (until the system clears it up).

**Comment by tsolar** [comment]
@unixmonkey thank you for the tips! I am going to test it and I will tell you how did it work!

**Comment by tsolar** [comment]
Pointing the master branch on my Gemfile gave me the exact same error.

Using another ruby version (we updated ruby version on the project to 2.7.2) and running: (after changing `close!` to `close`)

```bash
$ /home/tom/.rbenv/versions/2.7.2/gemsets/migrante-arc/bin/wkhtmltopdf --encoding UTF-8 
--lowquality /tmp/wicked_pdf20201117-191055-etmw35.html /tmp/wicked_pdf_generated_file20201117-191055-1g5sccj.pdf
Loading pages (1/6)
Floating point exception=======>                             ] 50%
```
That was the output using the master branch of the gem (set as you said, like `gem 'wicked_pdf', git: 'https://github.com/mileszs/wicked_pdf.git', branch: 'master'`) 

If I use system wkhtmltopdf it works:
```
$ /usr/bin/wkhtmltopdf --encoding UTF-8 --lowquality /tmp/wicked_pdf20201117-191055-etmw35.html /tmp/wicked_pdf_generated_file20201117-191055-1g5sccj.pdf
Loading page (1/2)
Printing pages (2/2)                                               
Done                                                           
```

**Comment by unixmonkey** [comment]
But does it work from the command-line using the gem `wkhtmltopdf` instead of your system `wkhtmltopdf`?

```shell
$ /home/tom/.rbenv/versions/2.7.2/gemsets/migrante-arc/bin/wkhtmltopdf --encoding UTF-8 --lowquality /tmp/wicked_pdf20201117-191055-etmw35.html /tmp/wicked_pdf_generated_file20201117-191055-1g5sccj.pdf
```

**Comment by tsolar** [comment]
No, I put the output on the previous reply

**Comment by unixmonkey** [comment]
Ok, that at least narrows it down to definitely not being a wicked_pdf issue. I do suspect it has something to do with an incompatibility between your system and the binary provided with the `wkhtmltopdf` gem you are using.

It could be an issue with QT, but could also be something with libpng or fonts or something like that. I did a web search for "wkhtmltopdf floating point exception" and turned up a few links worth investigating. It seems to be CSS related.

If that doesn't help, I'd recommend a removing things until it runs without issue to narrow down what's going on. Maybe remove all styling first. If that fixes things, add back half, and keep doing it until you've zeroed in on the issue.

**Comment by unixmonkey** [comment]
You may also want to add the `enable_local_file_access: true` option and see if that changes anything. That option is new to wkhtmltopdf 0.12.6.

**Comment by tsolar** [comment]
Thanks for your reply! I will try without CSS and related stuff. 

I have been tried with `enable_local_file_access: true` but the results were like the same. Most likely a CSS related stuff.

I'll let you know. Thank you!

**Comment by tellodaniel** [comment]
@tsolar did you find something? You found out it was a CSS problem?

I get the same error on 1 PDF generated out of 15 (average).

If someone can show some light to me I would appreciate. (@unixmonkey ?)

Here is my stack trace

```
RuntimeError: PDF could not be generated!
 Command Error: Loading pages (1/6)
[>                                                           ] 0%
[======>                                                     ] 10%
  from wicked_pdf (2.1.0) lib/wicked_pdf.rb:82:in `pdf_from_url'
  from wicked_pdf (2.1.0) lib/wicked_pdf.rb:38:in `pdf_from_html_file'
  from wicked_pdf (2.1.0) lib/wicked_pdf.rb:49:in `pdf_from_string'
  from wicked_pdf (2.1.0) lib/wicked_pdf/pdf_helper.rb:91:in `make_pdf'
  from wicked_pdf (2.1.0) lib/wicked_pdf/pdf_helper.rb:54:in `render_to_string_with_wicked_pdf'
  from wicked_pdf (2.1.0) lib/wicked_pdf/pdf_helper.rb:34:in `render_to_string'
  from app/helpers/amnesty_requests_helper.rb:26:in `render_pdf'
  from app/controllers/amnesty_requests_controller.rb:81:in `block (2 levels) in show'
  from actionpack (6.0.3.4) lib/action_controller/metal/mime_responds.rb:214:in `respond_to'
  from app/controllers/amnesty_requests_controller.rb:79:in `show'
  from actionpack (6.0.3.4) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
  from actionpack (6.0.3.4) lib/abstract_controller/base.rb:195:in `process_action'
  from actionpack (6.0.3.4) lib/action_controller/metal/rendering.rb:30:in `process_action'
  from actionpack (6.0.3.4) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
  from activesupport (6.0.3.4) lib/active_support/callbacks.rb:112:in `block in run_callbacks'
  from ahoy_matey (3.1.0) lib/ahoy/controller.rb:45:in `set_ahoy_request_store'
  from activesupport (6.0.3.4) lib/active_support/callbacks.rb:121:in `block in run_callbacks'
  from sentry-rails (4.1.1) lib/sentry/rails/controller_transaction.rb:7:in `block in included'
  from activesupport (6.0.3.4) lib/active_support/callbacks.rb:121:in `instance_exec'
  from activesupport (6.0.3.4) lib/active_support/callbacks.rb:121:in `block in run_callbacks'
  from activesupport (6.0.3.4) lib/active_support/callbacks.rb:139:in `run_callbacks'
  from actionpack (6.0.3.4) lib/abstract_controller/callbacks.rb:41:in `process_action'
  from actionpack (6.0.3.4) lib/action_controller/metal/rescue.rb:22:in `process_action'
  from actionpack (6.0.3.4) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
  from activesupport (6.0.3.4) lib/active_support/notifications.rb:180:in `block in instrument'
  from activesupport (6.0.3.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  from sentry-rails (4.1.1) lib/sentry/rails/tracing.rb:41:in `instrument'
  from activesupport (6.0.3.4) lib/active_support/notifications.rb:180:in `instrument'
  from actionpack (6.0.3.4) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
  from actionpack (6.0.3.4) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
  from activerecord (6.0.3.4) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
  from actionpack (6.0.3.4) lib/abstract_controller/base.rb:136:in `process'
  from actionview (6.0.3.4) lib/action_view/rendering.rb:39:in `process'
  from actionpack (6.0.3.4) lib/action_controller/metal.rb:190:in `dispatch'
  from actionpack (6.0.3.4) lib/action_controller/metal.rb:254:in `dispatch'
  from actionpack (6.0.3.4) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
  from actionpack (6.0.3.4) lib/action_dispatch/routing/route_set.rb:33:in `serve'
  from actionpack (6.0.3.4) lib/action_dispatch/journey/router.rb:49:in `block in serve'
  from actionpack (6.0.3.4) lib/action_dispatch/journey/router.rb:32:in `each'
  from actionpack (6.0.3.4) lib/action_dispatch/journey/router.rb:32:in `serve'
  from actionpack (6.0.3.4) lib/action_dispatch/routing/route_set.rb:834:in `call'
  from warden-jwt_auth (0.5.0) lib/warden/jwt_auth/middleware/token_dispatcher.rb:20:in `call'
  from warden-jwt_auth (0.5.0) lib/warden/jwt_auth/middleware/revocation_manager.rb:21:in `call'
  from rack (2.2.3) lib/rack/builder.rb:244:in `call'
  from warden-jwt_auth (0.5.0) lib/warden/jwt_auth/middleware.rb:23:in `call'
  from warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
  from warden (1.2.9) lib/warden/manager.rb:34:in `catch'
  from warden (1.2.9) lib/warden/manager.rb:34:in `call'
  from rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
  from google-cloud-debugger (0.36.3) lib/google/cloud/debugger/middleware.rb:151:in `call'
  from rack (2.2.3) lib/rack/etag.rb:27:in `call'
  from rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
  from rack (2.2.3) lib/rack/head.rb:12:in `call'
  from actionpack (6.0.3.4) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
  from rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
  from rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
  from actionpack (6.0.3.4) lib/action_dispatch/middleware/cookies.rb:648:in `call'
  from actionpack (6.0.3.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
  from activesupport (6.0.3.4) lib/active_support/callbacks.rb:101:in `run_callbacks'
  from actionpack (6.0.3.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
  from actionpack (6.0.3.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
  from actionpack (6.0.3.4) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
  from actionpack (6.0.3.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
  from railties (6.0.3.4) lib/rails/rack/logger.rb:37:in `call_app'
  from railties (6.0.3.4) lib/rails/rack/logger.rb:28:in `call'
  from ahoy_matey (3.1.0) lib/ahoy/engine.rb:22:in `call_with_quiet_ahoy'
  from google-cloud-logging (1.10.9) lib/google/cloud/logging/middleware.rb:97:in `call'
  from actionpack (6.0.3.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
  from actionpack (6.0.3.4) lib/action_dispatch/middleware/request_id.rb:27:in `call'
  from rack (2.2.3) lib/rack/method_override.rb:24:in `call'
  from rack (2.2.3) lib/rack/runtime.rb:22:in `call'
  from activesupport (6.0.3.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  from actionpack (6.0.3.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
  from actionpack (6.0.3.4) lib/action_dispatch/middleware/static.rb:126:in `call'
  from rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
  from actionpack (6.0.3.4) lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
  from sentry-ruby (4.1.1) lib/sentry/rack/capture_exceptions.rb:23:in `block in call'
  from sentry-ruby (4.1.1) lib/sentry/hub.rb:50:in `with_scope'
  from sentry-ruby (4.1.1) lib/sentry-ruby.rb:103:in `with_scope'
  from sentry-ruby (4.1.1) lib/sentry/rack/capture_exceptions.rb:14:in `call'
  from railties (6.0.3.4) lib/rails/engine.rb:527:in `call'
  from puma (4.3.6) lib/puma/configuration.rb:228:in `call'
  from puma (4.3.6) lib/puma/server.rb:713:in `handle_request'
  from puma (4.3.6) lib/puma/server.rb:472:in `process_client'
  from puma (4.3.6) lib/puma/server.rb:328:in `block in run'
  from puma (4.3.6) lib/puma/thread_pool.rb:134:in `block in spawn_thread'

```

**Comment by tsolar** [comment]
Sorry for the long delay.

In the project I am working, a coworker found that the problem was using
```css
@import "bootstrap/scss/bootstrap";
```
instead of 
```css
@import "bootstrap/scss/bootstrap.css";
```

So, to generate a PDF using WickedPDF, it's needed to add the extension.

This seems to solve the problem. Hope that helps!

**Comment by tsolar** [comment]
However, it's still weird that it works with the binary from Debian repos, but with the binary from the gem it doesn't...

**Comment by tellodaniel** [comment]
Thanks for your response @tsolar I managed to reduce our error ratio by removing all imported css. Instead I moved all styles to our html head tag. Definitely is not the best solution but this was affecting critical operations on out side.  

Just to add more info about the bug another thing I tried is adding all CSS from a CDN but had same problem.

**Comment by kalemi19** [comment]
I was facing the same issue and after hours of debugging, I noticed that one image URL I had included in the .erb template, was not reachable. 

It worked on my machine, so I initially thought that something was missing from the production server.

It turned out that the website had simply blocked the country my production server was located.

I solved the problem by manually checking whether the URL of the image can be accessed:

```
begin
      return SOME_PLACEHOLDER unless RestClient::Request.execute(method: :head, url: URL, timeout: 5, open_timeout: 5).code == 200
      URL
    rescue
      SOME_PLACEHOLDER
    end
```
