### ISSUE TITLE
version 2.1.0 broke rails 6.1.3

### ISSUE THREAD

**Issue by buncis** [mileszs/wicked_pdf#977]
## Issue description
when I do `rails s` it throwing

```
Completed 500 Internal Server Error in 6ms (ActiveRecord: 0.0ms | Allocations: 8247)


  
fatal (exception reentered):
  

UncaughtThrowError: uncaught throw :app_exception
        from /home/bc/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/web-console-4.1.0/lib/web_console/middleware.rb:134:in `throw'
        from /home/bc/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/web-console-4.1.0/lib/web_console/middleware.rb:134:in `rescue in call_app'
        from /home/bc/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/web-console-4.1.0/lib/web_console/middleware.rb:131:in `call_app'
        from /home/bc/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/web-console-4.1.0/lib/web_console/middleware.rb:28:in `block in call'
        from /home/bc/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/web-console-4.1.0/lib/web_console/middleware.rb:17:in `catch'
        from /home/bc/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/web-console-4.1.0/lib/web_console/middleware.rb:17:in `call'
        from /home/bc/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
        from /home/bc/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/rack/logger.rb:37:in `call_app'
        from /home/bc/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/rack/logger.rb:26:in `block in call'
        from /home/bc/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/tagged_logging.rb:99:in `block in tagged'
        from /home/bc/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/tagged_logging.rb:37:in `tagged'
        from /home/bc/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/tagged_logging.rb:99:in `tagged'
        from /home/bc/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/rack/logger.rb:26:in `call'
        from /home/bc/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sprockets-rails-3.2.2/lib/sprockets/rails/quiet_assets.rb:13:in `call'
        from /home/bc/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
        from /home/bc/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/request_id.rb:26:in `call'
        from /home/bc/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
        from /home/bc/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
        from /home/bc/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
        from /home/bc/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/executor.rb:14:in `call'
        from /home/bc/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/static.rb:24:in `call'
        from /home/bc/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
        from /home/bc/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/host_authorization.rb:98:in `call'
        from /home/bc/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-mini-profiler-2.3.2/lib/mini_profiler/profiler.rb:384:in `call'
        from /home/bc/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/webpacker-5.4.0/lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
        from /home/bc/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'
        from /home/bc/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-6.1.3.2/lib/rails/engine.rb:539:in `call'
        from /home/bc/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/puma-5.3.2/lib/puma/configuration.rb:249:in `call'
        from /home/bc/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/puma-5.3.2/lib/puma/request.rb:77:in `block in handle_request'
        from /home/bc/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/puma-5.3.2/lib/puma/thread_pool.rb:338:in `with_force_shutdown'
        from /home/bc/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/puma-5.3.2/lib/puma/request.rb:76:in `handle_request'
        from /home/bc/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/puma-5.3.2/lib/puma/server.rb:438:in `process_client'
        from /home/bc/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/puma-5.3.2/lib/puma/thread_pool.rb:145:in `block in spawn_thread'
```

## System specifications

wicked_pdf gem version: `2.1.0`

wkhtmltopdf version: `0.12.6`

platform/distribution and version: `ubuntu 21.04`

## Current Workaround

using 1.4.0 solving the problem

**Comment by mathieujobin** [comment]
I had a similar issue, I switch to the latest `master` branch, and it worked
if enough people confirm the fixed version, maybe we'll get an official release?

**Comment by unixmonkey** [comment]
Version 2.6.0 has been released. Please check against this version and reopen this issue if you are still having trouble.
